### ISSUE TITLE
Package does not work

### ISSUE THREAD

**Issue by alwins0n** [crhayes/blade-partials#1]
after install instructions request to the app fail.

php artisan dump-autoload outputs this:

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","me
ssage":"syntax error, unexpected '['","file":"...vendor\crhayes\blade-partials\src\Crhayes\BladePartials\Environment
.php","line":89}}{"error":{"type":"Symfony\Component\Debug\Exception\FatalEr
rorException","message":"syntax error, unexpected '['","file":"...vendor\crhayes\blade-partials\src\Crhayes\BladePart
ials\Environment.php","line":89}}

**Comment by crhayes** [comment]
Fixed by db54cf4f24ce15beb10070684663504cc4223aa5.
